Repository FEniCS/basix, pull requests merged in 2023-04, with the labels that each got.

#659 Use np.tile for blocked tabulation
  python/basix/ufl.py
  test/test_ufl_wrapper.py
Labels: bug

#660 Template polyset over float type
  .github/workflows/mac.yml
  cpp/basix/lattice.cpp
  cpp/basix/polyset.cpp
  cpp/basix/polyset.h
Labels: enhancement

#663 Support `float` and `double` in low-level functions
  .github/workflows/dolfin-tests.yml
  cpp/CMakeLists.txt
  cpp/basix/cell.cpp
  cpp/basix/cell.h
  cpp/basix/dof-transformations.cpp
  cpp/basix/dof-transformations.h
  cpp/basix/e-brezzi-douglas-marini.cpp
  cpp/basix/e-bubble.cpp
  cpp/basix/e-crouzeix-raviart.cpp
  cpp/basix/e-hermite.cpp
  cpp/basix/e-hhj.cpp
  cpp/basix/e-lagrange.cpp
  cpp/basix/e-nce-rtc.cpp
  cpp/basix/e-nedelec.cpp
  cpp/basix/e-raviart-thomas.cpp
  cpp/basix/e-regge.cpp
  cpp/basix/e-serendipity.cpp
  cpp/basix/finite-element.cpp
  cpp/basix/finite-element.h
  cpp/basix/interpolation.cpp
  cpp/basix/interpolation.h
  cpp/basix/lattice.cpp
  cpp/basix/lattice.h
  cpp/basix/math.cpp
  cpp/basix/math.h
  cpp/basix/moments.cpp
  cpp/basix/moments.h
  cpp/basix/polynomials.cpp
  cpp/basix/polynomials.h
  cpp/basix/precompute.cpp
  cpp/basix/precompute.h
  cpp/basix/quadrature.cpp
  cpp/basix/quadrature.h
  demo/cpp/demo_create_and_tabulate/main.cpp
  demo/cpp/demo_dof_transformations/main.cpp
  python/wrapper.cpp
Labels: enhancement

#664 Template `basix::FiniteElement` over scalar type
  .github/workflows/dolfin-tests.yml
  cpp/basix/cell.h
  cpp/basix/dof-transformations.cpp
  cpp/basix/e-brezzi-douglas-marini.cpp
  cpp/basix/e-brezzi-douglas-marini.h
  cpp/basix/e-bubble.cpp
  cpp/basix/e-bubble.h
  cpp/basix/e-crouzeix-raviart.cpp
  cpp/basix/e-crouzeix-raviart.h
  cpp/basix/e-hermite.cpp
  cpp/basix/e-hermite.h
  cpp/basix/e-hhj.cpp
  cpp/basix/e-hhj.h
  cpp/basix/e-lagrange.cpp
  cpp/basix/e-lagrange.h
  cpp/basix/e-nce-rtc.cpp
  cpp/basix/e-nce-rtc.h
  cpp/basix/e-nedelec.cpp
  cpp/basix/e-nedelec.h
  cpp/basix/e-raviart-thomas.cpp
  cpp/basix/e-raviart-thomas.h
  cpp/basix/e-regge.cpp
  cpp/basix/e-regge.h
  cpp/basix/e-serendipity.cpp
  cpp/basix/e-serendipity.h
  cpp/basix/element-families.h
  cpp/basix/finite-element.cpp
  cpp/basix/finite-element.h
  cpp/basix/indexing.h
  cpp/basix/interpolation.cpp
  cpp/basix/interpolation.h
  cpp/basix/lattice.cpp
  cpp/basix/moments.cpp
  cpp/basix/moments.h
  cpp/basix/polynomials.cpp
  cpp/basix/polyset.cpp
  cpp/basix/quadrature.cpp
  demo/cpp/demo_create_and_tabulate/main.cpp
  demo/cpp/demo_dof_transformations/main.cpp
  doc/cpp/index.md
  python/wrapper.cpp
  test/test_cmake/main.cpp
Labels: enhancement

#666 Update mdspan
  .github/workflows/dolfin-tests.yml
  cpp/basix/mdspan.hpp
Labels: housekeeping
