Repository FEniCS/basix, pull requests merged in 2023-10, with the labels that each got.

#676 Switch from pybind11 to nanobind
  INSTALL.md
  cpp/basix/cell.h
  cpp/basix/docs.h
  cpp/basix/finite-element.h
  cpp/generate_docs.py
  doc/README.md
  doc/cpp/Doxyfile
  doc/python/source/conf.py
  doc/python/source/index.rst
  pyproject.toml
  python/CMakeLists.txt
  python/basix/_basixcpp.pyi
  python/basix/cell.py
  python/basix/lattice.py
  python/basix/numba_helpers.py
  python/basix/quadrature.py
  python/basix/sobolev_spaces.py
  python/basix/ufl.py
  python/basix/variants.py
  python/pyproject.toml
  python/setup.py
  python/wrapper.cpp
  test/test_create.py
  test/test_custom_element.py
  test/test_dof_transformations.py
  test/test_lagrange.py
  test/test_numba.py
  test/test_orthonormal_basis.py
  test/test_ufl_wrapper.py
  test/test_version.py
Labels: enhancement, performance, task, proposal

#712 Add Spack test to CI
  .github/workflows/spack.yml
Labels: packaging, CI

#715 Remove `setup.py`
  .flake8
  CMakeLists.txt
  pyproject.toml
  python/CMakeLists.txt
  python/pyproject.toml
  python/setup.py
  setup.cfg
Labels: installation

#723 Add CI workflow trigger
  .github/workflows/pythonapp.yml
Labels: CI

#724 Improve nanobind bindings and memory management
  pyproject.toml
  python/CMakeLists.txt
  python/pyproject.toml
  python/wrapper.cpp
  setup.cfg
  test/test_continuity.py
  test/test_create.py
  test/test_custom_element.py
  test/test_dof_ordering.py
  test/test_dof_transformations.py
  test/test_entity_dofs.py
  test/test_equality.py
  test/test_hermite.py
  test/test_interpolation.py
  test/test_interpolation_between_elements.py
  test/test_iso.py
  test/test_lagrange.py
  test/test_mappings.py
  test/test_nedelec_second_kind.py
Labels: enhancement

#727 Use absolute imports in place of relative imports
  .github/workflows/dolfin-tests.yml
  python/basix/__init__.py
  python/basix/cell.py
  python/basix/finite_element.py
  python/basix/lattice.py
  python/basix/polynomials.py
  python/basix/quadrature.py
  python/basix/sobolev_spaces.py
  python/basix/variants.py
Labels: housekeeping

#728 Allow Spack ci to test specific Basix version
  .github/workflows/spack.yml
Labels: installation, CI
