Repository FEniCS/basix, pull requests merged in 2023-02, with the labels that each got.

#635 Dev version bumps
  setup.py
Labels: housekeeping

#639 Do not run apt-get upgrade in CI
  .github/workflows/pythonapp.yml
  .github/workflows/sonarcloud.yml
Labels: CI

#638 Fix typo in basix.sobolev_spaces module name
  cpp/basix/e-lagrange.cpp
  python/basix/ufl_wrapper.py
  python/wrapper.cpp
  test/test_ufl_wrapper.py
Labels: bug

#636 Fix degree method in UFL wrapper layer for mixed elements
  .github/workflows/ffcx-tests.yml
  .github/workflows/mac.yml
  .github/workflows/pythonapp.yml
  python/basix/ufl_wrapper.py
Labels: bug, high priority
