Repository FEniCS/basix, pull requests merged in 2023-11, with the labels that each got.

#720 Update install docs
  INSTALL.md
  README.md
  python/basix/__init__.py
Labels: documentation, installation

#730 Throw error when trying to create BDM degree 0
  cpp/basix/e-brezzi-douglas-marini.cpp
Labels: bug

#709 Update wheel build action.
  .github/workflows/build-wheels.yml
  python/CMakeLists.txt
Labels: packaging

#737 Enable merge queue
  .github/workflows/dolfin-tests.yml
  .github/workflows/ffcx-tests.yml
  .github/workflows/intel.yml
  .github/workflows/mac.yml
  .github/workflows/pythonapp.yml
  .github/workflows/redhat.yml
Labels: CI

#741 Add a `pip install --no-build-isolation` test
  .github/workflows/dolfinx-tests.yml
  .github/workflows/ffcx-tests.yml
  .github/workflows/intel.yml
  .github/workflows/mac.yml
  .github/workflows/pythonapp.yml
  .github/workflows/redhat.yml
  .github/workflows/sonarcloud.yml
  README.md
  pyproject.toml
  python/CMakeLists.txt
  python/pyproject.toml
Labels: CI

#745 Fix scikit-build-core version in `pyproject.toml`
  .github/workflows/redhat.yml
  pyproject.toml
  python/pyproject.toml
Labels: installation

#747 Use OpenBLAS in Redhat clone CI
  .github/workflows/redhat.yml
Labels: CI

#751 Do not store `.doctrees` binary files on website
  .github/workflows/pythonapp.yml
  doc/web/make_html.py
Labels: documentation, CI
