Repository FEniCS/basix, pull requests merged in 2024-04, with the labels that each got.

#799 Update `nb::ndarray` constructor in preparation of next nanobind release
  python/wrapper.cpp
Labels: nanobind, backport?

#802 Revise transformation names and add docs
  .github/workflows/dolfinx-tests.yml
  .github/workflows/pythonapp.yml
  cpp/basix/dof-transformations.h
  cpp/basix/finite-element.h
  cpp/basix/indexing.h
  cpp/basix/lattice.h
  cpp/basix/maps.h
  cpp/basix/math.h
  cpp/basix/polynomials.h
  cpp/basix/polyset.h
  cpp/basix/precompute.h
  cpp/basix/quadrature.cpp
  cpp/basix/quadrature.h
  demo/cpp/demo_dof_transformations/main.cpp
  python/basix/_basixcpp.pyi
  python/basix/finite_element.py
  python/basix/numba_helpers.py
  python/wrapper.cpp
  test/test_dof_transformations.py
  test/test_numba.py
Labels: documentation

#814 Remove commented code in CMake file
  python/CMakeLists.txt
Labels: housekeeping
